build:
  version: "3.0"

accounts:
  message: "Welcome to EmiBank accounts related local APIs "
  contactDetails:
    name: "Emmelie Johansson - Developer"
    email: "emmelie@emibank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
