build:
  version: "3.0"

cards:
  message: "Welcome to EmiBank cards related local APIs "
  contactDetails:
    name: "Emmelie Johansson - Developer"
    email: "emmelie@emibank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345