build:
  version: "1.0"

cards:
  message: "Welcome to EmiBank cards related prod APIs "
  contactDetails:
    name: "Andreas Olsson - Product Owner"
    email: "andreas@emibank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384